name: Build mobile platform
on:
  workflow_dispatch:
  push:
    paths:
      - 'VERSION'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86, x64, arm, arm64 ]
        target: [ android, cromite, cgms ]
    uses: ./.github/workflows/building.yaml
    with:
      ros: ubuntu-latest
      arch: ${{ matrix.arch }}
      target: ${{ matrix.target }}

  release:
    needs: build
    permissions:
      contents: write
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        arch: [ x86, x64, arm, arm64 ]
        target: [ android, cromite, cgms ]
    uses: ./.github/workflows/release.yaml
    with:
      ros: ubuntu-latest
      arch: ${{ matrix.arch }}
      target: ${{ matrix.target }}
